#! /bin/sh
#
######################################################################################
#     >>  Maintained by team Vitunix (https://github.com/vitunix)  <<                #
#             >> A Simple and unique Arch based distro <<                            #
#             -----> Mail us at (vitunix@proton.me) <-----                           #
#     ----> configured by heapbytes (https://github.com/heapbytes) <-----            #
######################################################################################
#

#pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config focused_border_color "#ffffff" 
bspc config normal_border_color "#000099"
bspc config active_border_color "#000099"
bspc config presel_feedback_color "#000099"

## ----- Add your stuff from here ------ ##
pkill sxhkd
sxhkd -c "$HOME/.config/bspwm/sxhkdrc" &

#$HOME/.screenlayout/display.sh
pkill picom
picom --config $HOME/.config/picom/picom.conf -b 

pkill polybar 
$HOME/.config/polybar/launch.sh &

#nitrogen --restore &
# Using feh bcuz it's fast 
feh --bg-scale $HOME/.config/wallpapers/waves.png
xsetroot -cursor_name left_ptr
picom -f &

# For betterlockscreen, this would run only once.
#$HOME/.config/vitunix-bin/lock-check.sh

